Repository ts-andrey/rslang, pull requests merged in 2022-03, with the labels that each got.

#49 fix the word selection error when calling the game from the tutorial
  src/scripts/audiocall/createArrayQuestions.ts
Labels: fix

#48 workbook fixes
  src/scripts/api/API.ts
  src/scripts/dictionary/Dictionary.ts
  src/scripts/dictionary/DictionaryView.ts
  src/scripts/dictionary/WordCard.ts
  src/scripts/manager/ViewManager.ts
  src/scripts/sprint/Sprint.ts
  src/scripts/sprint/SprintModel.ts
  src/scripts/sprint/SprintSettings.ts
  src/scripts/types/types.ts
Labels: fix, feature

#50 style improvements
  src/sass/util/_variables.scss
  src/scripts/burger/BurgerView.ts
  src/scripts/burger/burger.scss
  src/scripts/burger/burgerBuilder.ts
  src/scripts/burger/burgerSvg.ts
  src/scripts/header/header.scss
  src/scripts/header/headerBuilder.ts
  src/scripts/home/about/about.scss
  src/scripts/home/auth/authorize.scss
  src/scripts/home/features/features.scss
  src/scripts/home/info/info.scss
  src/scripts/home/review/review.scss
  src/scripts/home/team/team.scss
  src/scripts/statistics/daily.scss
  src/scripts/statistics/general.scss
  src/scripts/statistics/statistics.scss
Labels: enhancement

#52 fix: fix color-changing issue 2022-03-15 (19:55:56)
  src/scripts/audiocall/startAudiocall.ts
  src/scripts/sprint/Page.ts
Labels: fix
