Repository ts-andrey/rslang, pull requests merged in 2022-02, with the labels that each got.

#35 ignore learned words in the game
  src/sass/layout/main/games/_audiocall.scss
  src/scripts/audiocall/createArrayQuestions.ts
  src/scripts/audiocall/processAnswer.ts
  src/scripts/audiocall/showResult.ts
  src/scripts/audiocall/startQuestion.ts
  src/scripts/audiocall/startRound.ts
  src/scripts/audiocall/writeStatistics.ts
Labels: feature

#36 menu and start page adaptivness
  src/scripts/burger/burger.scss
  src/scripts/header/header.scss
  src/scripts/home/about/about.scss
  src/scripts/home/navigation/navigation.scss
Labels: enhancement

#38 get satistics
  src/scripts/audiocall/getStatistics.ts
  src/scripts/audiocall/writeStatistics.ts
Labels: feature

#39 fix team description
  src/scripts/audiocall/writeStatistics.ts
  src/scripts/home/team/TeamView.ts
Labels: fix

#40 info content basic adaptivness + statistics data attach to view
  src/scripts/footer/footer.scss
  src/scripts/header/headerBuilder.ts
  src/scripts/home/about/about.scss
  src/scripts/home/features/FeaturesView.ts
  src/scripts/home/features/features.scss
  src/scripts/home/features/featuresBuilder.ts
  src/scripts/home/info/info.scss
  src/scripts/home/team/team.scss
  src/scripts/statistics/DailyStatistics.ts
  src/scripts/statistics/StatisticsView.ts
  src/scripts/statistics/dailyBuilder.ts
Labels: bug, enhancement

#41 fix: shuffle answers
  src/scripts/audiocall/createArrayQuestions.ts
Labels: fix

#42 Sprint & Worbook (Final) (Hope so)
  src/sass/layout/main/_games.scss
  src/sass/layout/main/games/_sprint.scss
  src/sass/util/_variables.scss
  src/scripts/api/API.ts
  src/scripts/app.ts
  src/scripts/dictionary/Dictionary.ts
  src/scripts/dictionary/DictionaryModel.ts
  src/scripts/dictionary/DictionaryView.scss
  src/scripts/dictionary/DictionaryView.ts
  src/scripts/dictionary/DifficultyCard.scss
  src/scripts/dictionary/Pagination.scss
  src/scripts/dictionary/SmallWordCard.scss
  src/scripts/dictionary/WordCard.scss
  src/scripts/dictionary/WordCard.ts
  src/scripts/header/headerBuilder.ts
  src/scripts/manager/IViewManager.ts
  src/scripts/manager/ViewManager.ts
  src/scripts/sprint/ArrowButton.scss
  src/scripts/sprint/Badges.scss
  src/scripts/sprint/ColoredRing.ts
  src/scripts/sprint/ProgressRing.scss
  src/scripts/sprint/Sprint.ts
  src/scripts/sprint/SprintGameControls.scss
  src/scripts/sprint/SprintGameDisplay.scss
  src/scripts/sprint/SprintGameDisplay.ts
  src/scripts/sprint/SprintModel.ts
  src/scripts/sprint/SprintResultsButtons.scss
  src/scripts/sprint/SprintViewGame.scss
  src/scripts/sprint/SprintViewIntro.scss
  src/scripts/sprint/SprintViewResults.scss
  src/scripts/sprint/SprintViewShowWords.scss
  src/scripts/sprint/SprintWordLine.scss
  src/scripts/sprint/Timer.scss
  src/scripts/sprint/Timer.ts
  src/scripts/sprint/_sprint.scss
  src/scripts/types/types.ts
Labels: enhancement, fix, feature, refactor

#43 fix: fix statistics
  src/scripts/audiocall/writeStatistics.ts
Labels: fix

#44 attach git links in team page and add video review
  src/scripts/burger/BurgerView.ts
  src/scripts/burger/burgerBuilder.ts
  src/scripts/header/headerBuilder.ts
  src/scripts/home/review/ReviewView.ts
  src/scripts/home/review/review.scss
  src/scripts/home/team/TeamView.ts
  src/scripts/statistics/GeneralStatistics.ts
  src/scripts/statistics/StatisticsView.ts
  src/scripts/statistics/dailyBuilder.ts
Labels: enhancement, feature

#47 add auth and review adaptivness
  src/scripts/api/API.ts
  src/scripts/home/auth/authorize.scss
  src/scripts/home/review/review.scss
  src/scripts/sprint/Sprint.ts
  src/scripts/statistics/dailyBuilder.ts
Labels: enhancement
